from dskredhat/devops-test:php-V1
# run apt-get update && apt-get upgrade -y
RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli
# run apt-get install vim -y
copy index.php /var/www/html
expose 80